### ISSUE TITLE
文档目录树结构

### ISSUE THREAD

**Issue by CL0610** [calpa/gatsby-starter-calpa-blog#125]
![image](https://user-images.githubusercontent.com/29617295/50443578-fbe19c80-093e-11e9-94db-631d53bff9ef.png)
大多数hexo博客主题，对文章知识点采用分类标签扁平化的管理，如 xxx(6)这种样式，但是费大力气搭建博客是想构建 知识体系，以解决知识碎片化的问题。因此，从前端样式上，需要目录树的形式去承载这样的诉求，当然博主时间充足的话可以采用知识图谱的组件。这里说是采用React实现，是否意味着前端的页面可以自己去扩展，去利用开源的React组件去搭建自己想要的风格

**Comment by calpa** [comment]
我们可以在侧边栏加入标签组件，然后创建一些标签页面
