### ISSUE TITLE
请教一下楼主，graphql在GatsbyJS中的作用是什么？

### ISSUE THREAD

**Issue by zwl1619** [calpa/gatsby-starter-calpa-blog#132]
请教一下楼主，graphql在GatsbyJS中的作用是什么？用作前后端发送请求吗？

**Comment by calpa** [comment]
GraphQL 是作为前端获取数据的查询方法，发送请求还是用 axios 吧。。。

**Comment by zwl1619** [comment]
@calpa  
前端使用了GraphQL ，那服务端也必须要使用GraphQL来和前端GraphQL交互吧？
GraphQL在GatsbyJS中是必须要使用的吗？如果使用了axios，restful和GraphQL就同时存在了。

**Comment by calpa** [comment]
如果你的后端是使用 GraphQL 的话，那么你可以直接使用 `gatsby-source-graphql` 来调用后端提供的 GraphQL 接口。这样就无需 axios 和 restful。

比如说你需要调 Github 接口，那么你直接这样写查询语句就可以了：
```
{
  github {
    viewer {
      email
    }
  }
}
```

详见：https://www.gatsbyjs.org/packages/gatsby-source-graphql/

**Comment by zwl1619** [comment]
@calpa 
有点不太明白，如果后端没有使用GraphQL，那GraphQL在GatsbyJS中怎么能从后端获取数据？

**Comment by calpa** [comment]
继续用 restful

在 2019年2月1日週五 下午4:35，zwl1619 <notifications@github.com 寫道：
