### ISSUE TITLE
[优化]脚手架改进建议

### ISSUE THREAD

**Issue by Xeonice** [calpa/gatsby-starter-calpa-blog#164]
提一个小小的建议，作为脚手架工具，我认为内部代码不应当包含作者的私人信息，建议将 `src/contents` 文件夹下的个人 Blog 文章替换为示例文章，如 `HelloWorld` 之类的作为范例即可

**Comment by calpa** [comment]
@Xeonice 要不改一下构建脚本，在初始化的时候清空 `src/contents` 目录并生成 `HELLOWORLD.md`？

**Comment by Xeonice** [comment]
保证执行 `gatsby new awesome-blog https://github.com/calpa/gatsby-starter-calpa-blog` 的时候不包含作者个人信息即可

**Comment by calpa** [comment]
@Xeonice 已經按照建議調整腳手架默認配置
