### ISSUE TITLE
如何在使用 Netify 管理前端下，使用Contentful 作內容管理？

### ISSUE THREAD

**Issue by aforian** [calpa/gatsby-starter-calpa-blog#166]
**Is your feature request related to a problem? Please describe.**
如何在使用 Netify 管理前端下，使用Contentful 作內容管理？

**Describe alternatives you've considered**
想使用 Netify CMS + Contentful 寫作 的方式管理。

**Additional context**
在看過readme的教學後，順利地把blog建置在Netify上，瞭解現在的版本較偏向初心入門，所以使用md單文件的方式進行內容寫作。
而在看過作者的對Blog的介紹，知道作者之前是使用 Netify CMS + Contentful 的方式，把文章內容與前端進行分割。
所以我也想以這樣的方式，幫助不使用md單文件的朋友使用 Contentful 進行內容寫作。

想請問現在的版本，作者還是繼續使用 Netify CMS + Contentful 寫作 的方式管理嗎？
是使用 gatsby-source-contentful 套件來完成的嗎？

在網路上找到 gatsby+Netify+Contentful 的文章是使用 gatsby-source-contentful 的套件來完成，但在這個版本沒有看到該package的相依，想知道作者是不是使用另外的方法來達成，

另外有看到這個相關的ISSUE，但code of querying的連結已無法使用：
https://github.com/calpa/gatsby-starter-calpa-blog/issues/40

希望作者可以替我解惑，感恩

**Comment by baomoe** [comment]
我也想知道~haha

**Comment by calpa** [comment]
不好意思那麼晚才回覆你。

現在的博客系統已經沒有使用 Contentful，而是使用本地獲取 markdown，然後構建網站。

如果你是使用 Contentful 的話，那麼你可以直接使用 gatsby-source-contentful 來從 contentful 獲取文章，讓不使用 markdown 的朋友也可以使用。

那個時候好像是因為那個插件還沒有發布在社區裡面，所以我就自己寫了獲取 Contentful 數據的方法，具體可以看[去年 11 月份的版本的方法](https://github.com/calpa/gatsby-starter-calpa-blog/blob/828957c290a249a313bcab8b57f358f0d1fcb531/gatsby/getPosts.js)。
