### ISSUE TITLE
Fix pagination total page number

### ISSUE THREAD

**Issue by calpa** [calpa/gatsby-starter-calpa-blog#74]
**Describe the bug**
For now, the total page number is hard coded.

**To Reproduce**
1. Go to 'Home Page'
1. Scroll down to '1'
1. See error

**Expected behavior**
The total page number will be calculated during the producing of `pages` template.
If there is only one page, then return max number of pages = 1

**Screenshots**
![Imgur](https://i.imgur.com/DezBDK6.jpg)

**Additional context**

**Comment by iRuisu** [comment]
You could quite possibly set your 'maxPages' variable once you've called the 'getPosts' function within gatsby and then divide it by the max number of cards per page (6) then round it up?

**Comment by calpa** [comment]
@iRuisu you are right, just generate the maxPages variable in and the problem is solved.

For example, make it in [CreatePages.js](https://github.com/calpa/blog/blob/master/gatsby/CreatePages.js) file.

**Comment by frankmckechnie** [comment]
Hey there I just submitted a pull request hopefully this fixes the issue

**Comment by calpa** [comment]
Thank you, @frankmckechnie. Please reopen the pull request as 'feat-' prefix branch.

**Comment by calpa** [comment]
@frankmckechnie Can you open another pull request?

**Comment by frankmckechnie** [comment]
@calpa Hey I will try to do this now :)
